#! bin/bash

cd /tmp/fuse


echo "-------- Test12: Backup --------"

# make 5 files 
for i in {1..5}; do echo $i > $i.hejTobiasEllerMads; done;
echo the best group LOL > 4.hejTobiasEllerMads

mkdir subfolder
cd subfolder
# make 6 files 
for i in {1..6}; do echo $i > $i.hejTobiasEllerMads; done;

mkdir subsubfolder 
cd subsubfolder

# make 7 files 
for i in {1..7}; do echo $i > $i.awesomeFile; done;

cd /tmp/fuse/
echo " " 
echo Content of file 4.hejTobiasEllerMads in fuse: "$(cat 4.hejTobiasEllerMads)"
echo " " 
sleep 2
tree
sleep 9
echo "  "
echo "-------- backup now contains: --------"
tree ~/fusebackup/
echo " " 
sleep 4
echo Content of file 4.hejTobiasEllerMads in backup: "$(cat 4.hejTobiasEllerMads)"
echo " "
echo "-------- Reopening fuse & Clearing mount point data --------"

cd /tmp
fusermount -u /tmp/fuse
rm -r fuse/
mkdir fuse
chmod 755 fuse/
# Change path
cd /home/kristian/documents/4.-semester/file_system/assignment3/sources
./lfs /tmp/fuse


sleep 3
cd /tmp/fuse
echo " "
echo " IN FUSE: " 
tree /tmp/fuse
sleep 10
echo "Content of file 4.hejTobiasEllerMads in fuse: $(cat 4.hejTobiasEllerMads)"
echo " " 
sleep 3
echo "-------- Sucess --------"